NoteSpace /Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteSpace/NoteSpace.xcodeproj Couldn't load project at: /Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteSpace/NoteSpace.xcodeproj
/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/NoteSpace.xcodeproj Couldn't load project at: /Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/NoteSpace.xcodeproj

NoteSpace
/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteSpace/Generated/EditNoteNoteView.swift
/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteSpace/Generated/EditNoteNoteView.swift:5:19 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteSpace/Generated/EditNoteNoteView.swift:14:20 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteSpace/Generated/EditNoteNoteView.swift:69:31 Cannot find 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteSpace/Generated/EditNoteNoteView.swift:77:9 Referencing subscript 'subscript(dynamicMember:)' requires wrapper 'ObservedObject<NoteNoteViewModel>.Wrapper'

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteSpace/Generated/EditNoteNoteView.swift:77:27 Cannot call value of non-function type 'Binding<Subject>'

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteSpace/Generated/NoteNoteCard.swift
/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteSpace/Generated/NoteNoteCard.swift:4:19 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteSpace/Generated/NoteNoteViewModel.swift
/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteSpace/Generated/NoteNoteViewModel.swift:5:32 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteSpace/Generated/NoteNoteViewModel.swift:6:40 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteSpace/Generated/NoteNoteViewModel.swift:14:34 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteSpace/Generated/NoteNoteViewModel.swift:24:37 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteSpace/Generated/NoteNoteViewModel.swift:37:37 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/EditNoteView.swift
/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/EditNoteView.swift:5:15 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/EditNoteView.swift:14:16 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteCard.swift
/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteCard.swift:4:15 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteViewModel.swift
/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteViewModel.swift:5:28 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteViewModel.swift:6:36 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteViewModel.swift:14:26 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteViewModel.swift:24:29 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NoteViewModel.swift:37:29 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NotificationManager.swift
/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NotificationManager.swift:4:45 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/NotificationManager.swift:27:43 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/TagsView.swift
/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/TagsView.swift:10:36 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/TagsView.swift:63:21 Cannot find type 'NoteNote' in scope

/Users/workcar/Documents/gen project/NoteSpace/NoteSpace/Generated/NoteSpace/Generated/TagsView.swift:82:19 Cannot find type 'NoteNote' in scope